spring.application.name=concurrent-payment-service

spring.datasource.url=jdbc:postgresql://localhost:5433/paymentdb
spring.datasource.username=paymentuser
spring.datasource.password=paymentpass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

spring.flyway.enabled=true

management.endpoints.web.exposure.include=health,info